name: ToQa

on:
  push:
    branches: [ Qa ]
  pull_request:
    branches: [ Qa ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Config QA
        run: cp .env.qa .env
      - name: Config env
        run: |
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{secrets.QA_DB_HOST}}" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=${{secrets.QA_DB_DATABASE}}" >> .env
          echo "DB_USERNAME=${{secrets.QA_DB_USERNAME}}" >> .env
          echo "DB_PASSWORD=${{secrets.QA_DB_PASSWORD}}" >> .env
      - name: build php
        uses: nanasess/setup-php@v4
        with:
          php-version: '8.1'
      - run: composer install
      - name: Deploy files via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          # SFTP credentials
          host: ${{ secrets.FPT_SERVER }}
          port: 21
          user: ${{ secrets.FTP_USERNAME }}
          pass: ${{ secrets.FTP_PASSWORD }}
          # lftp settings
          onlyNewer: true
          settings: 'sftp:auto-confirm=yes'
          # Mirror command options
          localDir: '.'
          remoteDir: './test/'
          reverse: true
          ignoreFile: '.lftp_ignore'
          options: '--verbose'
      # - name: Deploy to FTP
      #   run: |
      #     lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} -e "set ftp:ssl-allow no; mirror --reverse --delete --only-newer -R /ruta/local /test" ${{ secrets.FPT_SERVER }}
      #   env:
      #     FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
      #     FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      #     FTP_HOST: ${{ secrets.FPT_SERVER }}

      # - name: Send to ftp server
      #   uses: joutvhu/ftp-transfer@v1
      #   with:
      #     host: ${{ secrets.FPT_SERVER }}
      #     port: 21
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     commands: put ./ ./test/


