name: ToQa

on:
  push:
    branches: [ Qa ]
  pull_request:
    branches: [ Qa ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Config QA
        run: cp .env.qa .env
      - name: Send to ftp server
        uses: joutvhu/ftp-transfer@v1
        with:
          host: ${{ secrets.FPT_SERVER }}
          port: 21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          commands: put ./ public_html/test/


